// <auto-generated />
namespace Durandal451v2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DicCategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DicCategories));
        
        string IMigrationMetadata.Id
        {
            get { return "201802091148492_DicCategories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
